### ISSUE TITLE
Moving window filter fails with non-square matrix

### ISSUE THREAD

**Issue by kevinpdavies** [cosmoharrigan/matrix-entropy#1]
moving_window_filter.py fails when a non-square matrix is used (see example below). This appears to be due to the height and width being set incorrectly in the first two lines:

```
matrix_width, matrix_height = matrix.shape

output_matrix = np.zeros([matrix_width - neighborhood_size + 1,
                          matrix_height - neighborhood_size + 1])
```

Should be:

```
matrix_height, matrix_width = matrix.shape

output_matrix = np.zeros([matrix_height - neighborhood_size + 1,
                          matrix_width - neighborhood_size + 1])
```

Example of error:

import numpy
from matrix_entropy import moving_window_filter as mwf
from matrix_entropy import neighborhood_functions as nf

dn = numpy.ma.ones((10,10)) # This is OK
mwf.moving_window_filter(matrix=dn, f=nf.avg_components, neighborhood_size=2)
dn = numpy.ma.ones((11,10)) # This is fails with IndexError: index out of bounds
mwf.moving_window_filter(matrix=dn, f=nf.avg_components, neighborhood_size=2)

**Comment by cosmoharrigan** [comment]
@kevinpdavies thank you for reporting this, and my apologies for the delay in responding. I have integrated your suggested change.
